# -*- coding: utf-8 -*-
"""RabTech_Task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ts3uFHhnBWQwolT1KdfdznaQZzIc3Z7v
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("daily-demand-series.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

# Convert date column

df["date"] = pd.to_datetime(df["date"])

# Sort by date

df = df.sort_values("date")

# Check missing values

print("Missing values:")
print(df.isnull().sum())

# Set date as index

df = df.set_index("date")

display(df.head())

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.plot(
    df.index,
    df["demand"],
    marker="o"
)

plt.title("Historical Daily Demand")
plt.xlabel("Date")
plt.ylabel("Demand")
plt.grid(True)

plt.show()

print("Descriptive Statistics")
display(df["demand"].describe())

from statsmodels.tsa.seasonal import seasonal_decompose

decomposition = seasonal_decompose(
    df["demand"],
    model="additive",
    period=7
)

fig = decomposition.plot()

fig.set_size_inches(12, 10)

plt.show()

from statsmodels.tsa.stattools import adfuller

adf_result = adfuller(df["demand"])

print("ADF Statistic:", adf_result[0])
print("p-value:", adf_result[1])

print("\nCritical Values:")

for key, value in adf_result[4].items():
    print(key, ":", value)

if adf_result[1] < 0.05:
    print("\nConclusion: The series is stationary.")
else:
    print("\nConclusion: The series is non-stationary.")

df["demand_diff"] = df["demand"].diff()

differenced = df["demand_diff"].dropna()

adf_diff = adfuller(differenced)

print("ADF Statistic after differencing:",
      adf_diff[0])

print("p-value after differencing:",
      adf_diff[1])

plt.figure(figsize=(12, 5))

plt.plot(
    differenced,
    marker="o"
)

plt.title("Differenced Daily Demand")
plt.xlabel("Date")
plt.ylabel("Differenced Demand")
plt.grid(True)

plt.show()

test_size = 7

train = df["demand"].iloc[:-test_size]
test = df["demand"].iloc[-test_size:]

print("Training observations:", len(train))
print("Testing observations:", len(test))

from statsmodels.tsa.arima.model import ARIMA

results = []

for p in range(0, 4):
    for d in range(0, 2):
        for q in range(0, 4):

            try:

                model = ARIMA(
                    train,
                    order=(p, d, q)
                )

                fitted = model.fit()

                results.append({
                    "p": p,
                    "d": d,
                    "q": q,
                    "AIC": fitted.aic
                })

            except:
                pass

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "AIC"
)

display(results_df)

best = results_df.iloc[0]

best_p = int(best["p"])
best_d = int(best["d"])
best_q = int(best["q"])

print(
    f"Best ARIMA model: "
    f"ARIMA({best_p},{best_d},{best_q})"
)

print("Best AIC:", best["AIC"])

best_model = ARIMA(
    train,
    order=(best_p, best_d, best_q)
)

best_model_fit = best_model.fit()

print(best_model_fit.summary())

# Generate predictions for the test data

test_forecast = best_model_fit.forecast(
    steps=len(test)
)

# Make sure forecast uses the same dates as test data
test_forecast.index = test.index

print("Test forecast generated successfully!")

display(
    pd.DataFrame({
        "Actual": test,
        "Predicted": test_forecast
    })
)

# Train the selected ARIMA model

best_model = ARIMA(
    train,
    order=(best_p, best_d, best_q)
)

best_model_fit = best_model.fit()

print("ARIMA model trained successfully!")
print(f"Model: ARIMA({best_p}, {best_d}, {best_q})")

def calculate_mape(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)

    return np.mean(
        np.abs((actual - predicted) / actual)
    ) * 100


mape = calculate_mape(
    test,
    test_forecast
)

print("MAPE:", round(mape, 2), "%")

from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        test,
        test_forecast
    )
)

print("RMSE:", round(rmse, 4))

plt.figure(figsize=(12, 5))

plt.plot(
    train.index,
    train,
    label="Training Data"
)

plt.plot(
    test.index,
    test,
    marker="o",
    label="Actual Test Data"
)

plt.plot(
    test.index,
    test_forecast,
    marker="o",
    linestyle="--",
    label="Predicted Data"
)

plt.title("ARIMA: Actual vs Predicted Demand")
plt.xlabel("Date")
plt.ylabel("Demand")

plt.legend()
plt.grid(True)

plt.show()