# -*- coding: utf-8 -*-
"""RabTech_Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUN8HuEdA90f2kDsHIv8hY2s3XcUWf0M
"""



"""# Dimensionality Reduction & Unsupervised Clustering

## Aim

To apply Principal Component Analysis (PCA) for dimensionality reduction and use K-Means, DBSCAN, and Hierarchical clustering to discover patterns in a high-dimensional dataset.
"""

# Import required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score

from scipy.cluster.hierarchy import dendrogram, linkage

import plotly.express as px

print("Libraries imported successfully!")

# Load Iris dataset

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add actual species for reference only
df["species"] = [
    iris.target_names[i]
    for i in iris.target
]

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

"""## Dataset Description

The Iris dataset contains 150 flower observations and four numerical features:

1. Sepal length
2. Sepal width
3. Petal length
4. Petal width

There are three known species: Setosa, Versicolor, and Virginica.

The species labels will not be used during clustering because clustering is an unsupervised learning technique.
"""

print("Dataset information:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nSummary statistics:")
display(df.describe())

# Select numerical features only

features = iris.feature_names

X = df[features]

print("Features used for clustering:")
print(features)

print("\nShape of X:", X.shape)

"""## Standardization

Before PCA and clustering, the numerical features are standardized using StandardScaler.

Standardization transforms each feature so that it has approximately:

- Mean = 0
- Standard deviation = 1

This prevents features with larger scales from dominating the analysis.
"""

# Standardize the data

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Standardization completed.")

print("Mean after standardization:")
print(np.round(X_scaled.mean(axis=0), 4))

print("\nStandard deviation after standardization:")
print(np.round(X_scaled.std(axis=0), 4))

"""## Principal Component Analysis (PCA)

PCA is a dimensionality reduction technique.

It transforms the original correlated features into a smaller number of uncorrelated principal components.

The first principal component captures the maximum possible variance, the second captures the next highest variance, and so on.
"""

# Apply PCA with all components

pca = PCA()

X_pca = pca.fit_transform(X_scaled)

print("Original number of features:", X_scaled.shape[1])
print("Number of principal components:", X_pca.shape[1])

# Explained variance ratio

explained_variance = pca.explained_variance_ratio_

print("Explained Variance Ratio:")
for i, value in enumerate(explained_variance, start=1):
    print(f"PC{i}: {value:.4f}")

print("\nCumulative Explained Variance:")

cumulative_variance = np.cumsum(explained_variance)

for i, value in enumerate(cumulative_variance, start=1):
    print(f"PC1-PC{i}: {value:.4f}")

# Cumulative Explained Variance Plot

# Calculate cumulative explained variance
cumulative_variance = np.cumsum(pca.explained_variance_ratio_)

# Create component numbers
components = range(1, len(pca.explained_variance_ratio_) + 1)

# Plot
plt.figure(figsize=(8, 5))

plt.plot(
    components,
    cumulative_variance,
    marker="o"
)

plt.xlabel("Number of Principal Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("Cumulative Explained Variance")

plt.xticks(list(components))
plt.grid(True)

plt.show()

# PCA with 2 components

pca_2d = PCA(n_components=2)

X_pca_2d = pca_2d.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    X_pca_2d,
    columns=["PC1", "PC2"]
)

pca_df.head()

plt.figure(figsize=(9, 6))

sns.scatterplot(
    x="PC1",
    y="PC2",
    data=pca_df,
    s=80
)

plt.title("2D PCA Projection")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()

"""## K-Means Clustering

K-Means is an unsupervised clustering algorithm that divides observations into K clusters.

The algorithm:

1. Selects K cluster centers.
2. Assigns observations to the nearest center.
3. Recalculates cluster centers.
4. Repeats until the clusters stabilize.
"""

# Elbow Method

inertia = []

K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)

    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))

plt.plot(
    K_range,
    inertia,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")

plt.xticks(K_range)
plt.grid(True)

plt.show()

# Calculate Silhouette Scores for different K values

silhouette_scores = []

K_range = range(2, 11)

for k in K_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    silhouette_scores.append(score)

    print(f"K = {k}, Silhouette Score = {score:.4f}")

# Silhouette Score Plot

plt.figure(figsize=(8, 5))

plt.plot(
    list(K_range),
    silhouette_scores,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score Analysis")

plt.xticks(list(K_range))
plt.grid(True)

plt.show()

# Find K with the highest Silhouette Score

best_index = np.argmax(silhouette_scores)
best_k = list(K_range)[best_index]
best_score = silhouette_scores[best_index]

print("Best K:", best_k)
print("Highest Silhouette Score:", round(best_score, 4))

# Apply K-Means using the best K

kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

kmeans_labels = kmeans.fit_predict(X_scaled)

print("K-Means clustering completed successfully!")
print("Optimal K:", best_k)

print("\nCluster counts:")
print(
    pd.Series(kmeans_labels)
    .value_counts()
    .sort_index()
)

# Add K-Means cluster labels to PCA dataset

pca_df["KMeans_Cluster"] = kmeans_labels

print("Cluster labels added successfully!")

display(pca_df.head())

# 2D K-Means cluster visualization

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="KMeans_Cluster",
    palette="deep",
    s=80
)

plt.title("K-Means Clusters in PCA Space")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(title="Cluster")

plt.show()

# Silhouette score for final K-Means model

kmeans_silhouette = silhouette_score(
    X_scaled,
    kmeans_labels
)

print("Final K-Means Silhouette Score:",
      round(kmeans_silhouette, 4))

"""## K-Means Result

K-Means clustering was performed using the optimal number of clusters determined from the Silhouette Score analysis.

The clusters were projected onto the first two principal components for visualization.

A higher Silhouette Score indicates better-defined and more separated clusters.
"""

# PCA with 3 components

pca_3d = PCA(n_components=3)

X_pca_3d = pca_3d.fit_transform(X_scaled)

pca_3d_df = pd.DataFrame(
    X_pca_3d,
    columns=["PC1", "PC2", "PC3"]
)

# Add K-Means labels
pca_3d_df["KMeans_Cluster"] = kmeans_labels

display(pca_3d_df.head())

# Interactive 3D K-Means visualization

fig = px.scatter_3d(
    pca_3d_df,
    x="PC1",
    y="PC2",
    z="PC3",
    color="KMeans_Cluster",
    title="3D PCA Projection with K-Means Clusters"
)

fig.show()

# DBSCAN clustering

dbscan = DBSCAN(
    eps=0.6,
    min_samples=5
)

dbscan_labels = dbscan.fit_predict(X_scaled)

print("DBSCAN clustering completed!")

print(
    "Number of clusters:",
    len(set(dbscan_labels)) -
    (1 if -1 in dbscan_labels else 0)
)

print(
    "Number of noise points:",
    list(dbscan_labels).count(-1)
)

# Add DBSCAN labels

pca_df["DBSCAN_Cluster"] = dbscan_labels

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="DBSCAN_Cluster",
    palette="deep",
    s=80
)

plt.title("DBSCAN Clusters in PCA Space")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()