# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOQbFZpw0XRM0KPFQkjIENYW0imFhZ37
"""

import numpy as np
import pandas as pd
import scipy
from scipy.stats import pearsonr, spearmanr
from scipy import stats
from sklearn.linear_model import LinearRegression

print("Libraries imported successfully!")

# Set seed for reproducibility
np.random.seed(42)

# Number of students
n = 100

# Generate study hours
study_hours = np.random.uniform(1, 30, n)

# Generate exam scores
exam_scores = (
    40
    + 1.8 * study_hours
    + np.random.normal(0, 8, n)
)

# Keep scores between 0 and 100
exam_scores = np.clip(exam_scores, 0, 100)

# Create DataFrame
data = pd.DataFrame({
    "study_hours": study_hours,
    "exam_score": exam_scores
})

print("Synthetic dataset created successfully!")
print("Number of observations:", len(data))

data.head()

data.to_csv("synthetic_raw_data.csv", index=False)

print("Raw synthetic data saved successfully.")

# Remove missing values
processed_data = data.dropna().copy()

# Apply predefined inclusion rules
processed_data = processed_data[
    (processed_data["study_hours"] >= 0) &
    (processed_data["study_hours"] <= 60) &
    (processed_data["exam_score"] >= 0) &
    (processed_data["exam_score"] <= 100)
]

print("Original observations:", len(data))
print("Processed observations:", len(processed_data))
print("Excluded observations:", len(data) - len(processed_data))

print("Descriptive Statistics")
print("======================")

print("\nStudy Hours:")
print(processed_data["study_hours"].describe())

print("\nExam Score:")
print(processed_data["exam_score"].describe())

pearson_r, pearson_p = pearsonr(
    processed_data["study_hours"],
    processed_data["exam_score"]
)

print("Pearson Correlation")
print("===================")
print("Correlation (r):", round(pearson_r, 4))
print("p-value:", round(pearson_p, 6))

spearman_rho, spearman_p = spearmanr(
    processed_data["study_hours"],
    processed_data["exam_score"]
)

print("Spearman Correlation")
print("====================")
print("Correlation (rho):", round(spearman_rho, 4))
print("p-value:", round(spearman_p, 6))

X = processed_data[["study_hours"]]
y = processed_data["exam_score"]

model = LinearRegression()

model.fit(X, y)

intercept = model.intercept_
coefficient = model.coef_[0]
r_squared = model.score(X, y)

print("Linear Regression")
print("=================")

print("Intercept:", round(intercept, 4))
print("Study-hours coefficient:", round(coefficient, 4))
print("R-squared:", round(r_squared, 4))

import statsmodels.api as sm

X_reg = sm.add_constant(processed_data["study_hours"])
model_sm = sm.OLS(processed_data["exam_score"], X_reg).fit()

print(model_sm.summary())

import statsmodels.api as sm

X_reg = sm.add_constant(processed_data["study_hours"])
model_sm = sm.OLS(processed_data["exam_score"], X_reg).fit()

print(model_sm.summary())

alpha = 0.05

print("Final Decision")
print("==============")

if pearson_p < alpha:
    print("Reject H₀.")
    print("There is a statistically significant relationship between")
    print("study hours and exam scores.")
else:
    print("Fail to reject H₀.")
    print("There is not enough evidence of a statistically significant")
    print("relationship between study hours and exam scores.")

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

plt.scatter(
    processed_data["study_hours"],
    processed_data["exam_score"]
)

plt.xlabel("Study Hours per Week")
plt.ylabel("Exam Score")
plt.title("Study Hours vs Exam Score")

plt.show()

# Synthetic pipeline validation

assert len(data) == 100

assert "study_hours" in data.columns
assert "exam_score" in data.columns

assert data["study_hours"].notna().all()
assert data["exam_score"].notna().all()

assert data["study_hours"].between(0, 60).all()
assert data["exam_score"].between(0, 100).all()

assert len(processed_data) > 0

print("Synthetic pipeline test PASSED!")
print("All expected output contracts are satisfied.")

import sys
import numpy
import pandas
import scipy
import sklearn
import statsmodels

print("Python:", sys.version)
print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("SciPy:", scipy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Statsmodels:", statsmodels.__version__)