# -*- coding: utf-8 -*-
"""RabTech_Task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bM4LqfaPx6EvkjZWgZoc7CHEA-3eUc0J
"""



"""# Time-Series Forecasting with ARIMA

## Aim

To analyze historical daily demand data, identify trend and seasonality, test stationarity using the Augmented Dickey-Fuller (ADF) test, apply differencing when required, build and select an ARIMA model, evaluate its forecasting performance using MAPE and RMSE, and generate a 30-day future demand forecast.
"""

# Import required libraries

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA

from sklearn.metrics import mean_squared_error

print("Libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("daily-demand-series.csv")

print("Dataset loaded successfully!")
display(df.head())

df = pd.read_csv("daily-demand-series.csv")

print("Dataset loaded successfully!")
display(df.head())

print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nLast 5 records:")
display(df.tail())

# Convert date to datetime

df["date"] = pd.to_datetime(df["date"])

# Sort by date

df = df.sort_values("date")

# Set date as index

df = df.set_index("date")

print("Date conversion completed!")

display(df.head())

print("Date range:")
print("Start:", df.index.min())
print("End:", df.index.max())

print("\nNumber of observations:", len(df))

print("\nDate differences:")
print(df.index.to_series().diff().value_counts())

plt.figure(figsize=(12, 5))

plt.plot(
    df.index,
    df["demand"],
    marker="o"
)

plt.title("Daily Demand Over Time")
plt.xlabel("Date")
plt.ylabel("Demand")
plt.grid(True)

plt.show()

fig, ax1 = plt.subplots(figsize=(12, 5))

ax1.plot(
    df.index,
    df["demand"],
    marker="o"
)

ax1.set_xlabel("Date")
ax1.set_ylabel("Demand")

ax2 = ax1.twinx()

ax2.bar(
    df.index,
    df["marketing_event"],
    alpha=0.3
)

ax2.set_ylabel("Marketing Event")

plt.title("Demand and Marketing Events")

plt.show()

plt.figure(figsize=(12, 4))

plt.plot(
    df.index,
    df["demand"],
    marker="o",
    label="Demand"
)

holiday_dates = df[df["holiday"] == 1]

plt.scatter(
    holiday_dates.index,
    holiday_dates["demand"],
    s=100,
    label="Holiday"
)

plt.title("Demand and Holidays")
plt.xlabel("Date")
plt.ylabel("Demand")
plt.legend()
plt.grid(True)

plt.show()

"""## Time-Series Decomposition

Time-series decomposition separates the observed series into:

1. Trend – long-term movement.
2. Seasonality – repeating pattern.
3. Residual – random/unexplained variation.

Since the data is daily, a period of 7 is used to represent a possible weekly seasonal pattern.
"""

# Time-series decomposition

decomposition = seasonal_decompose(
    df["demand"],
    model="additive",
    period=7
)

fig = decomposition.plot()

fig.set_size_inches(12, 10)

plt.show()

"""## Augmented Dickey-Fuller (ADF) Test

The ADF test checks whether a time series is stationary.

### Hypotheses

H₀: The time series has a unit root and is non-stationary.

H₁: The time series is stationary.

### Decision Rule

If p-value < 0.05:
Reject H₀ → series is stationary.

If p-value ≥ 0.05:
Fail to reject H₀ → series is non-stationary.
"""

# ADF test

adf_result = adfuller(df["demand"])

print("Augmented Dickey-Fuller Test")
print("===========================")

print("ADF Statistic:", round(adf_result[0], 4))
print("p-value:", adf_result[1])

print("\nCritical Values:")

for key, value in adf_result[4].items():
    print(f"{key}: {value:.4f}")

if adf_result[1] < 0.05:
    print("\nConclusion: The series is stationary.")
else:
    print("\nConclusion: The series is non-stationary.")

# First-order differencing

df["demand_diff"] = df["demand"].diff()

display(df[["demand", "demand_diff"]].head(10))

# ADF test after differencing

differenced_data = df["demand_diff"].dropna()

adf_diff = adfuller(differenced_data)

print("ADF Test After Differencing")
print("===========================")

print("ADF Statistic:", round(adf_diff[0], 4))
print("p-value:", adf_diff[1])

if adf_diff[1] < 0.05:
    print("\nConclusion: Differenced series is stationary.")
else:
    print("\nConclusion: Differenced series is still non-stationary.")

plt.figure(figsize=(12, 5))

plt.plot(
    differenced_data,
    marker="o"
)

plt.title("First-Differenced Demand")
plt.xlabel("Date")
plt.ylabel("Differenced Demand")

plt.grid(True)

plt.show()

# Train-test split

test_size = 7

train = df["demand"].iloc[:-test_size]
test = df["demand"].iloc[-test_size:]

print("Training observations:", len(train))
print("Testing observations:", len(test))

print("\nTraining period:")
print(train.index.min(), "to", train.index.max())

print("\nTesting period:")
print(test.index.min(), "to", test.index.max())

plt.figure(figsize=(12, 5))

plt.plot(
    train.index,
    train,
    marker="o",
    label="Training Data"
)

plt.plot(
    test.index,
    test,
    marker="o",
    label="Test Data"
)

plt.title("Train-Test Split")
plt.xlabel("Date")
plt.ylabel("Demand")

plt.legend()
plt.grid(True)

plt.show()

# ARIMA hyperparameter selection using AIC

results = []

# Use d = 1 if original data is non-stationary
d_value = 1

for p in range(0, 4):
    for q in range(0, 4):

        try:
            model = ARIMA(
                train,
                order=(p, d_value, q)
            )

            fitted_model = model.fit()

            results.append({
                "p": p,
                "d": d_value,
                "q": q,
                "AIC": fitted_model.aic
            })

        except:
            pass

arima_results = pd.DataFrame(results)

arima_results = arima_results.sort_values("AIC")

display(arima_results)

# Select model with lowest AIC

best_model_row = arima_results.iloc[0]

best_p = int(best_model_row["p"])
best_d = int(best_model_row["d"])
best_q = int(best_model_row["q"])

print("Best ARIMA order:")
print(
    f"ARIMA({best_p}, {best_d}, {best_q})"
)

print("Lowest AIC:",
      round(best_model_row["AIC"], 4))

# Fit best ARIMA model

best_arima = ARIMA(
    train,
    order=(best_p, best_d, best_q)
)

best_arima_fit = best_arima.fit()

print(best_arima_fit.summary())

# Forecast test period

test_forecast = best_arima_fit.forecast(
    steps=len(test)
)

test_forecast.index = test.index

display(
    pd.DataFrame({
        "Actual": test,
        "Predicted": test_forecast
    })
)

# RMSE

rmse = np.sqrt(
    mean_squared_error(
        test,
        test_forecast
    )
)

print("RMSE:", round(rmse, 4))

# MAPE

def calculate_mape(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)

    return np.mean(
        np.abs(
            (actual - predicted) / actual
        )
    ) * 100


mape = calculate_mape(
    test,
    test_forecast
)

print("MAPE:", round(mape, 2), "%")

plt.figure(figsize=(12, 5))

plt.plot(
    train.index,
    train,
    label="Training"
)

plt.plot(
    test.index,
    test,
    marker="o",
    label="Actual Test"
)

plt.plot(
    test.index,
    test_forecast,
    marker="o",
    linestyle="--",
    label="Forecast"
)

plt.title("ARIMA Forecast vs Actual Demand")
plt.xlabel("Date")
plt.ylabel("Demand")

plt.legend()
plt.grid(True)

plt.show()

# Train final model using all available data

final_model = ARIMA(
    df["demand"],
    order=(best_p, best_d, best_q)
)

final_model_fit = final_model.fit()

print("Final ARIMA model trained successfully!")
print(
    f"Model: ARIMA({best_p}, {best_d}, {best_q})"
)

# Generate 30-day future forecast

forecast_steps = 30

future_forecast = final_model_fit.get_forecast(
    steps=forecast_steps
)

forecast_mean = future_forecast.predicted_mean
confidence_interval = future_forecast.conf_int()

print("30-Day Future Forecast")
print("======================")

display(
    pd.DataFrame({
        "Forecast": forecast_mean
    })
)

plt.figure(figsize=(14, 6))

# Historical data
plt.plot(
    df.index,
    df["demand"],
    marker="o",
    label="Historical Demand"
)

# Forecast
plt.plot(
    forecast_mean.index,
    forecast_mean,
    marker="o",
    linestyle="--",
    label="30-Day Forecast"
)

# Confidence interval
plt.fill_between(
    forecast_mean.index,
    confidence_interval.iloc[:, 0],
    confidence_interval.iloc[:, 1],
    alpha=0.2,
    label="95% Confidence Interval"
)

plt.title("30-Day Demand Forecast using ARIMA")
plt.xlabel("Date")
plt.ylabel("Demand")

plt.legend()
plt.grid(True)

plt.show()

# Save forecast to CSV

forecast_df = pd.DataFrame({
    "date": forecast_mean.index,
    "forecast_demand": forecast_mean.values,
    "lower_95_ci": confidence_interval.iloc[:, 0].values,
    "upper_95_ci": confidence_interval.iloc[:, 1].values
})

forecast_df.to_csv(
    "30_day_demand_forecast.csv",
    index=False
)

print("30-day forecast saved successfully!")

display(forecast_df.head())

"""# Final Findings

## 1. Historical Trend

The historical daily demand series was analyzed to identify its overall trend and possible seasonal behavior.

## 2. Time-Series Decomposition

The series was decomposed into observed, trend, seasonal, and residual components using a weekly period of 7 days.

## 3. Stationarity

The Augmented Dickey-Fuller test was used to determine whether the original demand series was stationary.

If the original series was non-stationary, first-order differencing was applied.

## 4. ARIMA Model

Several ARIMA(p,d,q) combinations were evaluated using AIC.

The model with the lowest AIC was selected as the final model for the test evaluation.

## 5. Model Evaluation

The model was evaluated using the final 7 days as the test set.

### Evaluation Metrics

- RMSE: [insert value obtained from Colab]
- MAPE: [insert value obtained from Colab]

Lower RMSE and MAPE indicate better forecasting performance.

## 6. 30-Day Forecast

The selected ARIMA model was retrained using the complete historical dataset and used to generate a 30-day future demand forecast.

A 95% confidence interval was also calculated to represent forecast uncertainty.

## Conclusion

The ARIMA model successfully demonstrated an end-to-end time-series forecasting pipeline, including time-series decomposition, stationarity testing, differencing, model selection, forecast evaluation, and 30-day future prediction.
"""