# -*- coding: utf-8 -*-
"""RabTech_Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zN3wRmQ8xuIyYR8w0V5Ig4STSh6wCSOb
"""

# Import required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from scipy.stats import shapiro, kstest
from scipy.stats import ttest_ind, mannwhitneyu

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from sklearn.datasets import load_iris

print("All libraries imported successfully!")

# Load Iris dataset

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add species name
df["species"] = [
    iris.target_names[i]
    for i in iris.target
]

df.head()

print("Dataset shape:", df.shape)

print("\nDataset information:")
print(df.info())

print("\nSpecies counts:")
print(df["species"].value_counts())

print("\nSummary statistics:")
display(df.describe())

"""## Hypotheses

### Normality Tests

**H₀:** The sample comes from a normally distributed population.

**H₁:** The sample does not come from a normally distributed population.

### Two-Sample t-Test

**H₀:** The mean petal length of Setosa and Versicolor flowers is equal.

**H₁:** The mean petal length of Setosa and Versicolor flowers is different.

### Mann-Whitney U Test

**H₀:** The distributions of petal length for Setosa and Versicolor are equal.

**H₁:** The distributions of petal length for Setosa and Versicolor are different.

### One-Way ANOVA

**H₀:** The mean petal length is equal across all three species.

**H₁:** At least one species has a different mean petal length.

### Two-Way ANOVA

**H₀:** Species, petal-width category, and their interaction have no significant effect on petal length.

**H₁:** At least one factor or interaction has a significant effect on petal length.

### Significance Level

α = 0.05

### Decision Rule

* If **p < 0.05** → Reject H₀.
* If **p ≥ 0.05** → Fail to reject H₀.

A 95% confidence level will be used for confidence intervals.

"""

# Distribution plot of petal length

plt.figure(figsize=(8, 5))

sns.histplot(
    df["petal length (cm)"],
    kde=True
)

plt.title("Distribution of Petal Length")
plt.xlabel("Petal Length (cm)")
plt.ylabel("Frequency")

plt.show()

# Q-Q plot

plt.figure(figsize=(7, 5))

stats.probplot(
    df["petal length (cm)"],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot of Petal Length")

plt.show()

# Shapiro-Wilk normality test

stat, p_value = shapiro(df["petal length (cm)"])

print("Shapiro-Wilk Test")
print("-----------------")
print("Test statistic:", round(stat, 4))
print("p-value:", p_value)

if p_value < 0.05:
    print("Reject H0: Data is not normally distributed.")
else:
    print("Fail to reject H0: No significant evidence against normality.")

# Standardize the petal length data

standardized_data = stats.zscore(
    df["petal length (cm)"]
)

# Kolmogorov-Smirnov test

ks_stat, ks_p = kstest(
    standardized_data,
    "norm"
)

print("Kolmogorov-Smirnov Test")
print("-----------------------")
print("Test statistic:", round(ks_stat, 4))
print("p-value:", ks_p)

if ks_p < 0.05:
    print("Reject H0: Data is not normally distributed.")
else:
    print("Fail to reject H0: No significant evidence against normality.")

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df[df["species"].isin(["setosa", "versicolor"])],
    x="species",
    y="petal length (cm)"
)

plt.title("Petal Length: Setosa vs Versicolor")
plt.xlabel("Species")
plt.ylabel("Petal Length (cm)")

plt.show()

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df[df["species"].isin(["setosa", "versicolor"])],
    x="species",
    y="petal length (cm)"
)

plt.title("Petal Length: Setosa vs Versicolor")
plt.xlabel("Species")
plt.ylabel("Petal Length (cm)")

plt.show()

# Select Setosa and Versicolor petal length

setosa = df[df["species"] == "setosa"]["petal length (cm)"]

versicolor = df[df["species"] == "versicolor"]["petal length (cm)"]

print("Setosa values:", len(setosa))
print("Versicolor values:", len(versicolor))

# Independent two-sample t-test

t_stat, t_p = ttest_ind(
    setosa,
    versicolor,
    equal_var=False
)

print("Independent Two-Sample t-Test")
print("-----------------------------")
print("t-statistic:", round(t_stat, 4))
print("p-value:", t_p)

if t_p < 0.05:
    print("Reject H0.")
    print("There is a statistically significant difference")
    print("between the two group means.")
else:
    print("Fail to reject H0.")
    print("There is no statistically significant difference")
    print("between the two group means.")

from scipy.stats import ttest_ind

t_stat, t_p = ttest_ind(
    setosa,
    versicolor,
    equal_var=False
)

print("Independent Two-Sample t-Test")
print("-----------------------------")
print("t-statistic:", round(t_stat, 4))
print("p-value:", t_p)

if t_p < 0.05:
    print("Reject H0.")
    print("There is a statistically significant difference")
    print("between the two group means.")
else:
    print("Fail to reject H0.")
    print("There is no statistically significant difference")
    print("between the two group means.")

